select * from cutomer limit 20

--what is total revenue generated by male vs female customers?
select gender,
SUM(purchase_amount) as revenue
from cutomer
group by gender

--which customers use a discount but still spend more than the average purchase amount?
select customer_id,
purchase_amount
from cutomer
where discount_applied = 'Yes'
and purchase_amount >= (select AVG(purchase_amount) from cutomer)

--which are top 5 products with the highest average review rating?
select 
item_purchased,
ROUND(AVG(review_rating::numeric),2) as average_prod_rating
from cutomer
group by item_purchased
order by avg(review_rating) desc
limit 5

--compare the average purchase amount between standard and express shipping?
select shipping_type,
round(AVG(purchase_amount),2)
from cutomer
where shipping_type in ('Standard','Express')
group by shipping_type

--do subscribed customers spend more? compare average spend and total revenue
--between subscribers and non-subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from cutomer
group by subscription_status
order by total_revenue,avg_spend

--which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' then 1 else 0 end)/count(*), 2) as discount_rate
from cutomer
group by item_purchased
order by discount_rate desc
limit 5

--segment customers into New, Returning, an Loyal based on their total
--number of previous purchases and show the count of each segment
with cutomer_type as (
select customer_id,
previous_purchases,
CASE 
  WHEN previous_purchases = 1 THEN 'New'
  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
  ELSE 'Loyal'
  END AS customer_segment
FROM cutomer
)

select customer_segment,
 count(*) as number_of_customers
from cutomer_type
group by customer_segment

--what are the top 3 most purchased products within each category?
with item_counts as(select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC)as item_rank
from cutomer
group by category, item_purchased)

select 
item_rank,
category,
item_purchased,
total_orders
from item_counts
where item_rank <=3

--are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) AS repeat_buyers
from cutomer
where previous_purchases >5
group by subscription_status

--what is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from cutomer
group by age_group
order by total_revenue desc
